USE EMS
GO

DROP TABLE IF EXISTS T_EMPLOYEE;
DROP TABLE IF EXISTS T_GRADES;

CREATE TABLE T_GRADES(
    S_GRADE_ID NVARCHAR(10) PRIMARY KEY,
    S_POSITION NVARCHAR(500)
)
GO

CREATE TABLE T_EMPLOYEE(
    S_EMPLOYEE_ID NVARCHAR(50) PRIMARY KEY,
    S_FIRST_NAME NVARCHAR(50),
    S_LAST_NAME NVARCHAR(50),
    S_GENDER CHAR,
    D_DOB DATETIME,
    S_RESUME NVARCHAR(500),
    D_DOJ DATETIME,
    S_SUPERVISOR NVARCHAR(50),
    S_GRADE_ID NVARCHAR(10),
    FOREIGN KEY (S_GRADE_ID) REFERENCES T_GRADES(S_GRADE_ID),
    FOREIGN KEY (S_SUPERVISOR) REFERENCES T_EMPLOYEE(S_EMPLOYEE_ID)
)